/**
 * Turns src/content/* into supabase/seed.sql, so the database is populated from
 * exactly the same data the static fallback renders — no hand-written INSERTs
 * to drift out of sync.
 *
 *   npm run seed:sql
 *
 * The content modules are TypeScript, but they only ever use `import type`,
 * which Node erases outright — so plain type stripping is enough to load them.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const ROOT = path.resolve(import.meta.dirname, "..");

const load = (relative) => import(pathToFileURL(path.join(ROOT, relative)).href);

const { projects } = await load("src/content/projects.ts");
const { galleries, posters } = await load("src/content/media.ts");
const { profile, experience, education, skillGroups } = await load("src/content/profile.ts");

/** Single-quoted SQL literal, or NULL. */
const q = (value) =>
  value === undefined || value === null || value === "" ? "NULL" : `'${String(value).replace(/'/g, "''")}'`;

/** jsonb literal. */
const j = (value) => `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;

const bool = (value) => (value ? "true" : "false");
const num = (value) => (value === undefined || value === null ? "NULL" : String(value));

const lines = [];
const write = (line = "") => lines.push(line);

write("-- ============================================================================");
write("--  Seed data — generated by scripts/generate-seed.mjs. Do not edit by hand.");
write(`--  Generated ${new Date().toISOString()}`);
write("--");
write("--  Safe to re-run: every section replaces what it inserted last time.");
write("-- ============================================================================");
write();
write("begin;");
write();

// ------------------------------------------------------------------- profile --
write("-- ------------------------------------------------------------- profile --");
write("delete from public.profile;");
write(`insert into public.profile
  (name, title, tagline, bio, email, phone, location,
   github, linkedin, leetcode, codeforces,
   cv_url, portrait_url, portrait_wide_url, languages)
values (
  ${q(profile.name)},
  ${q(profile.title)},
  ${q(profile.tagline)},
  ${j(profile.bio)},
  ${q(profile.email)},
  ${q(profile.phone)},
  ${q(profile.location)},
  ${q(profile.github)},
  ${q(profile.linkedin)},
  ${q(profile.leetcode)},
  ${q(profile.codeforces)},
  ${q(profile.cvUrl)},
  ${q(profile.portraitUrl)},
  ${q(profile.portraitWideUrl)},
  ${j(profile.languages)}
);`);
write();

// ---------------------------------------------------------------- experience --
write("-- ---------------------------------------------------------- experience --");
write("delete from public.experience;");
for (const item of experience) {
  write(`insert into public.experience (role, company, location, period, current, bullets, sort_order)
values (${q(item.role)}, ${q(item.company)}, ${q(item.location)}, ${q(item.period)}, ${bool(item.current)}, ${j(item.bullets)}, ${item.sortOrder});`);
}
write();

// ----------------------------------------------------------------- education --
write("-- ----------------------------------------------------------- education --");
write("delete from public.education;");
for (const item of education) {
  write(`insert into public.education (title, institution, location, period, detail, sort_order)
values (${q(item.title)}, ${q(item.institution)}, ${q(item.location)}, ${q(item.period)}, ${q(item.detail)}, ${item.sortOrder});`);
}
write();

// --------------------------------------------------------------- skill groups --
write("-- -------------------------------------------------------- skill groups --");
write("delete from public.skill_groups;");
for (const group of skillGroups) {
  write(`insert into public.skill_groups (name, items, sort_order)
values (${q(group.name)}, ${j(group.items)}, ${group.sortOrder});`);
}
write();

// ------------------------------------------------------------------ projects --
write("-- ------------------------------------------------------------ projects --");
write("-- Child rows cascade, so deleting the project clears its media/tech/etc.");
const slugList = projects.map((p) => q(p.slug)).join(", ");
write(`delete from public.projects where slug in (${slugList});`);
write();

for (const project of projects) {
  const media = project.media.length > 0 ? project.media : (galleries[project.slug] ?? []);

  write(`-- ${project.title} ${"-".repeat(Math.max(0, 62 - project.title.length))}`);

  // A WITH clause may only be followed by one statement, so every child insert
  // becomes a data-modifying CTE hanging off `p` and the last one is the
  // statement itself.
  const cte = [`p as (
  insert into public.projects
    (slug, title, subtitle, summary, body, role, category, period, year,
     featured, sort_order, status, repo_url, live_url, paper_url,
     cover_url, video_url, poster_url, architecture)
  values (
    ${q(project.slug)},
    ${q(project.title)},
    ${q(project.subtitle)},
    ${q(project.summary)},
    ${j(project.body)},
    ${q(project.role)},
    ${q(project.category)},
    ${q(project.period)},
    ${num(project.year)},
    ${bool(project.featured)},
    ${project.sortOrder},
    ${q(project.status)},
    ${q(project.repoUrl)},
    ${q(project.liveUrl)},
    ${q(project.paperUrl)},
    ${q(project.coverUrl)},
    ${q(project.videoUrl)},
    ${q(posters[project.slug])},
    ${project.architecture ? j(project.architecture) : "NULL"}
  )
  returning id
)`];

  const parts = [];

  if (project.metrics.length) {
    parts.push(`insert into public.project_metrics (project_id, label, value, sort_order)
select p.id, v.label, v.value, v.ord from p, (values
${project.metrics.map((m, i) => `  (${q(m.label)}, ${q(m.value)}, ${i})`).join(",\n")}
) as v(label, value, ord)`);
  }

  if (project.highlights.length) {
    parts.push(`insert into public.project_highlights (project_id, label, detail, sort_order)
select p.id, v.label, v.detail, v.ord from p, (values
${project.highlights.map((h, i) => `  (${q(h.label)}, ${q(h.detail)}, ${i})`).join(",\n")}
) as v(label, detail, ord)`);
  }

  if (project.decisions?.length) {
    parts.push(`insert into public.project_decisions (project_id, title, detail, sort_order)
select p.id, v.title, v.detail, v.ord from p, (values
${project.decisions.map((d, i) => `  (${q(d.title)}, ${q(d.detail)}, ${i})`).join(",\n")}
) as v(title, detail, ord)`);
  }

  if (project.tech.length) {
    parts.push(`insert into public.project_tech (project_id, name, version, kind, note, sort_order)
select p.id, v.name, v.version, v.kind, v.note, v.ord from p, (values
${project.tech.map((t, i) => `  (${q(t.name)}, ${q(t.version)}, ${q(t.kind)}, ${q(t.note)}, ${i})`).join(",\n")}
) as v(name, version, kind, note, ord)`);
  }

  if (media.length) {
    parts.push(`insert into public.project_media (project_id, url, caption, kind, sort_order)
select p.id, v.url, v.caption, v.kind, v.ord from p, (values
${media.map((m, i) => `  (${q(m.url)}, ${q(m.caption)}, ${q(m.kind)}, ${i})`).join(",\n")}
) as v(url, caption, kind, ord)`);
  }

  if (parts.length === 0) {
    write(`with ${cte[0]}\nselect id from p;`);
  } else {
    const named = parts.slice(0, -1).map((part, i) => `ins${i} as (\n${part}\n  returning 1\n)`);
    write(`with ${[...cte, ...named].join(",\n")}\n${parts.at(-1)};`);
  }
  write();
}

write("commit;");
write();

const sql = lines.join("\n");
await writeFile(path.join(ROOT, "supabase", "seed.sql"), sql, "utf8");

// setup.sql is schema + seed in one file, so first-time setup is a single paste
// into the SQL editor. Generated, so it cannot drift from its two halves.
const schema = await readFile(path.join(ROOT, "supabase", "schema.sql"), "utf8");
await writeFile(
  path.join(ROOT, "supabase", "setup.sql"),
  [
    "-- ============================================================================",
    "--  Complete setup — schema then seed, generated by scripts/generate-seed.mjs.",
    "--  Paste this whole file into the Supabase SQL editor and run it once.",
    "--  Safe to re-run.",
    "-- ============================================================================",
    "",
    schema,
    "",
    sql,
  ].join("\n"),
  "utf8",
);

const mediaTotal = projects.reduce(
  (n, p) => n + (p.media.length || (galleries[p.slug] ?? []).length),
  0,
);
console.log("Wrote supabase/seed.sql and supabase/setup.sql");
console.log(
  `  ${projects.length} projects · ${mediaTotal} media rows · ` +
    `${experience.length} roles · ${education.length} education · ${skillGroups.length} skill groups`,
);
